// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package middlewaresmocks

import (
	"context"

	"github.com/a-novel/service-authentication/internal/services"
	"github.com/a-novel/service-json-keys/models"
	"github.com/a-novel/service-json-keys/pkg"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthClaimsVerifier creates a new instance of MockAuthClaimsVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthClaimsVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthClaimsVerifier {
	mock := &MockAuthClaimsVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthClaimsVerifier is an autogenerated mock type for the AuthClaimsVerifier type
type MockAuthClaimsVerifier struct {
	mock.Mock
}

type MockAuthClaimsVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthClaimsVerifier) EXPECT() *MockAuthClaimsVerifier_Expecter {
	return &MockAuthClaimsVerifier_Expecter{mock: &_m.Mock}
}

// VerifyClaims provides a mock function for the type MockAuthClaimsVerifier
func (_mock *MockAuthClaimsVerifier) VerifyClaims(ctx context.Context, usage models.KeyUsage, accessToken string, options *pkg.VerifyClaimsOptions) (*services.AccessTokenClaims, error) {
	ret := _mock.Called(ctx, usage, accessToken, options)

	if len(ret) == 0 {
		panic("no return value specified for VerifyClaims")
	}

	var r0 *services.AccessTokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.KeyUsage, string, *pkg.VerifyClaimsOptions) (*services.AccessTokenClaims, error)); ok {
		return returnFunc(ctx, usage, accessToken, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.KeyUsage, string, *pkg.VerifyClaimsOptions) *services.AccessTokenClaims); ok {
		r0 = returnFunc(ctx, usage, accessToken, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.AccessTokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.KeyUsage, string, *pkg.VerifyClaimsOptions) error); ok {
		r1 = returnFunc(ctx, usage, accessToken, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthClaimsVerifier_VerifyClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyClaims'
type MockAuthClaimsVerifier_VerifyClaims_Call struct {
	*mock.Call
}

// VerifyClaims is a helper method to define mock.On call
//   - ctx context.Context
//   - usage models.KeyUsage
//   - accessToken string
//   - options *pkg.VerifyClaimsOptions
func (_e *MockAuthClaimsVerifier_Expecter) VerifyClaims(ctx interface{}, usage interface{}, accessToken interface{}, options interface{}) *MockAuthClaimsVerifier_VerifyClaims_Call {
	return &MockAuthClaimsVerifier_VerifyClaims_Call{Call: _e.mock.On("VerifyClaims", ctx, usage, accessToken, options)}
}

func (_c *MockAuthClaimsVerifier_VerifyClaims_Call) Run(run func(ctx context.Context, usage models.KeyUsage, accessToken string, options *pkg.VerifyClaimsOptions)) *MockAuthClaimsVerifier_VerifyClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.KeyUsage
		if args[1] != nil {
			arg1 = args[1].(models.KeyUsage)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *pkg.VerifyClaimsOptions
		if args[3] != nil {
			arg3 = args[3].(*pkg.VerifyClaimsOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthClaimsVerifier_VerifyClaims_Call) Return(accessTokenClaims *services.AccessTokenClaims, err error) *MockAuthClaimsVerifier_VerifyClaims_Call {
	_c.Call.Return(accessTokenClaims, err)
	return _c
}

func (_c *MockAuthClaimsVerifier_VerifyClaims_Call) RunAndReturn(run func(ctx context.Context, usage models.KeyUsage, accessToken string, options *pkg.VerifyClaimsOptions) (*services.AccessTokenClaims, error)) *MockAuthClaimsVerifier_VerifyClaims_Call {
	_c.Call.Return(run)
	return _c
}
