packages:
  github.com/a-novel/service-authentication/internal/services:
    config:
      all: true
      pkgname: servicesmocks
      dir: internal/services/mocks
      filename: mocks.go
  github.com/a-novel/service-authentication/internal/api:
    config:
      all: true
      pkgname: apimocks
      dir: internal/api/mocks
      filename: mocks.go
  github.com/a-novel/service-authentication/pkg:
    config:
      all: true
      pkgname: pkgmocks
      dir: pkg/mocks
      filename: mocks.go
