// Code generated by ogen, DO NOT EDIT.

package apimodels

// OperationName is the ogen operation name
type OperationName = string

const (
	CheckSessionOperation         OperationName = "CheckSession"
	CreateAnonSessionOperation    OperationName = "CreateAnonSession"
	CreateSessionOperation        OperationName = "CreateSession"
	EmailExistsOperation          OperationName = "EmailExists"
	GetUserOperation              OperationName = "GetUser"
	HealthcheckOperation          OperationName = "Healthcheck"
	ListUsersOperation            OperationName = "ListUsers"
	PingOperation                 OperationName = "Ping"
	RefreshSessionOperation       OperationName = "RefreshSession"
	RegisterOperation             OperationName = "Register"
	RequestEmailUpdateOperation   OperationName = "RequestEmailUpdate"
	RequestPasswordResetOperation OperationName = "RequestPasswordReset"
	RequestRegistrationOperation  OperationName = "RequestRegistration"
	ResetPasswordOperation        OperationName = "ResetPassword"
	UpdateEmailOperation          OperationName = "UpdateEmail"
	UpdatePasswordOperation       OperationName = "UpdatePassword"
	UpdateRoleOperation           OperationName = "UpdateRole"
)
