// Code generated by ogen, DO NOT EDIT.
package apimodels

type CheckSessionRes interface {
	checkSessionRes()
}

type CreateAnonSessionRes interface {
	createAnonSessionRes()
}

type CreateSessionRes interface {
	createSessionRes()
}

type EmailExistsRes interface {
	emailExistsRes()
}

type GetUserRes interface {
	getUserRes()
}

type HealthcheckRes interface {
	healthcheckRes()
}

type ListUsersRes interface {
	listUsersRes()
}

type PingRes interface {
	pingRes()
}

type RefreshSessionRes interface {
	refreshSessionRes()
}

type RegisterRes interface {
	registerRes()
}

type RequestEmailUpdateRes interface {
	requestEmailUpdateRes()
}

type RequestPasswordResetRes interface {
	requestPasswordResetRes()
}

type RequestRegistrationRes interface {
	requestRegistrationRes()
}

type ResetPasswordRes interface {
	resetPasswordRes()
}

type UpdateEmailRes interface {
	updateEmailRes()
}

type UpdatePasswordRes interface {
	updatePasswordRes()
}

type UpdateRoleRes interface {
	updateRoleRes()
}
