package lib

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"math"
	"runtime"
	"strings"

	"golang.org/x/crypto/argon2"
)

var (
	ErrInvalidHash         = errors.New("the encoded hash is in an invalid format")
	ErrIncompatibleVersion = errors.New("the encoded hash is using an incompatible version of Argon2")
	ErrInvalidPassword     = errors.New("the password is invalid")
)

const (
	argon2HashLen = 6
)

// Default parameters for Argon2id, following https://www.rfc-editor.org/rfc/rfc9106.html#section-7.4
// recommendations.
//
// We use the second recommendation for resources optimization.
const (
	Argon2IterationsDefault = 3
	Argon2MemoryDefault     = 64 * 1024
	Argon2SaltLenDefault    = 32
	Argon2KeyLenDefault     = 32
)

// Argon2Params contains the parameters used to generate a hash using the Argon2id algorithm.
//
// You can use Argon2ParamsDefault unless you have specific requirements.
type Argon2Params struct {
	// Memory is the amount of memory used by the Argon2 algorithm (in kibibytes).
	Memory uint32
	// Iterations is the number of passes over the memory.
	Iterations uint32
	// Parallelism is the number of threads (or lanes) used by the algorithm. Uses the runtime cpus count by default.
	Parallelism uint8
	// SaltLength is the length of the random salt. 16 bytes is recommended for password hashing.
	SaltLength uint
	// KeyLength is the length of the generated key (or password hash). 16 bytes or more is recommended.
	KeyLength uint32
}

var Argon2ParamsDefault = Argon2Params{
	Memory:     Argon2MemoryDefault,
	Iterations: Argon2IterationsDefault,
	SaltLength: Argon2SaltLenDefault,
	KeyLength:  Argon2KeyLenDefault,
}

// GenerateArgon2 generates a secure hash using the Argon2id algorithm.
// This is similar to bcrypt.GenerateFromPassword but uses the more modern Argon2 algorithm.
func GenerateArgon2(password string, params Argon2Params) (string, error) {
	// Generate a cryptographically secure random salt.
	salt := make([]byte, params.SaltLength)

	_, err := io.ReadFull(rand.Reader, salt)
	if err != nil {
		return "", fmt.Errorf("generate salt: %w", err)
	}

	// Set to number of available CPUs by default.
	if params.Parallelism == 0 {
		nCpus := runtime.NumCPU()
		// Prevent overflow, even though it should hardly happen lol.
		if nCpus > math.MaxUint8 {
			nCpus = math.MaxUint8
		}

		params.Parallelism = uint8(nCpus)
	}

	// Pass the plaintext password, salt and parameters to the argon2.IDKey
	// function. This will generate a hash of the password using the Argon2id
	// variant.
	hash := argon2.IDKey(
		[]byte(password),
		salt,
		params.Iterations,
		params.Memory,
		params.Parallelism,
		params.KeyLength,
	)

	b64Salt := base64.RawStdEncoding.EncodeToString(salt)
	b64Hash := base64.RawStdEncoding.EncodeToString(hash)

	// Return a string using the standard encoded hash representation.
	encodedHash := fmt.Sprintf(
		"$argon2id$v=%d$m=%d,t=%d,p=%d$%s$%s",
		argon2.Version,
		params.Memory,
		params.Iterations,
		params.Parallelism,
		b64Salt,
		b64Hash,
	)

	return encodedHash, nil
}

// CompareArgon2 compares a password with an encoded hash generated by GenerateArgon2.
// It returns nil if the password matches, or ErrInvalidPassword otherwise.
//
// This is similar to bcrypt.CompareHashAndPassword but uses the more modern Argon2 algorithm.
func CompareArgon2(password, encodedHash string) error {
	// Extract the parameters, salt and derived key from the encoded password hash.
	params, salt, hash, err := decodeHash(encodedHash)
	if err != nil {
		return fmt.Errorf("decode hash: %w", err)
	}

	// Derive the key from the other password using the same parameters.
	otherHash := argon2.IDKey(
		[]byte(password),
		salt,
		params.Iterations,
		params.Memory,
		params.Parallelism,
		params.KeyLength,
	)

	// Check that the contents of the hashed passwords are identical. Note
	// that we are using the subtle.ConstantTimeCompare() function for this
	// to help prevent timing attacks.
	if subtle.ConstantTimeCompare(hash, otherHash) == 1 {
		return nil
	}

	return ErrInvalidPassword
}

func decodeHash(encodedHash string) (*Argon2Params, []byte, []byte, error) {
	values := strings.Split(encodedHash, "$")
	if len(values) != argon2HashLen {
		return nil, nil, nil, ErrInvalidHash
	}

	var version int

	_, err := fmt.Sscanf(values[2], "v=%d", &version)
	if err != nil {
		err = errors.Join(ErrInvalidHash, err)

		return nil, nil, nil, fmt.Errorf("parse version: %w", err)
	}

	if version != argon2.Version {
		return nil, nil, nil, ErrIncompatibleVersion
	}

	params := &Argon2Params{}

	_, err = fmt.Sscanf(values[3], "m=%d,t=%d,p=%d", &params.Memory, &params.Iterations, &params.Parallelism)
	if err != nil {
		err = errors.Join(ErrInvalidHash, err)

		return nil, nil, nil, fmt.Errorf("parse parameters: %w", err)
	}

	salt, err := base64.RawStdEncoding.Strict().DecodeString(values[4])
	if err != nil {
		err = errors.Join(ErrInvalidHash, err)

		return nil, nil, nil, fmt.Errorf("decode salt: %w", err)
	}

	params.SaltLength = uint(len(salt))

	hash, err := base64.RawStdEncoding.Strict().DecodeString(values[5])
	if err != nil {
		err = errors.Join(ErrInvalidHash, err)

		return nil, nil, nil, fmt.Errorf("decode hash: %w", err)
	}

	rawHashLength := len(hash)
	if rawHashLength > math.MaxUint32 {
		return nil, nil, nil, fmt.Errorf("%w: hash length: %d", ErrInvalidHash, rawHashLength)
	}

	params.KeyLength = uint32(rawHashLength)

	return params, salt, hash, nil
}
