// Code generated by ogen, DO NOT EDIT.

package codegen

// OperationName is the ogen operation name
type OperationName = string

const (
	CheckSessionOperation         OperationName = "CheckSession"
	CreateAnonSessionOperation    OperationName = "CreateAnonSession"
	CreateRefreshTokenOperation   OperationName = "CreateRefreshToken"
	CreateSessionOperation        OperationName = "CreateSession"
	EmailExistsOperation          OperationName = "EmailExists"
	GetPublicKeyOperation         OperationName = "GetPublicKey"
	HealthcheckOperation          OperationName = "Healthcheck"
	ListPublicKeysOperation       OperationName = "ListPublicKeys"
	PingOperation                 OperationName = "Ping"
	RefreshSessionOperation       OperationName = "RefreshSession"
	RegisterOperation             OperationName = "Register"
	RequestEmailUpdateOperation   OperationName = "RequestEmailUpdate"
	RequestPasswordResetOperation OperationName = "RequestPasswordReset"
	RequestRegistrationOperation  OperationName = "RequestRegistration"
	ResetPasswordOperation        OperationName = "ResetPassword"
	UpdateEmailOperation          OperationName = "UpdateEmail"
	UpdatePasswordOperation       OperationName = "UpdatePassword"
)
