sender:
  name: Agora des Écrivains
  email: ${SMTP_SENDER}
  password: ${SMTP_PASSWORD}
  domain: ${SMTP_DOMAIN}
addr: S{SMTP_ADDRESS}
sandbox: ${SMTP_SANDBOX}
urls:
  updateEmail: ${AUTH_PLATFORM_URL_UPDATE_EMAIL}
  updatePassword: ${AUTH_PLATFORM_URL_UPDATE_PASSWORD}
  register: ${AUTH_PLATFORM_URL_REGISTER}
