// Code generated by mockery v2.53.1. DO NOT EDIT.

package servicesmocks

import (
	context "github.com/a-novel-kit/context"
	dao "github.com/a-novel/authentication/internal/dao"
	mock "github.com/stretchr/testify/mock"

	models "github.com/a-novel/authentication/models"
)

// MockSearchKeysSource is an autogenerated mock type for the SearchKeysSource type
type MockSearchKeysSource struct {
	mock.Mock
}

type MockSearchKeysSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchKeysSource) EXPECT() *MockSearchKeysSource_Expecter {
	return &MockSearchKeysSource_Expecter{mock: &_m.Mock}
}

// SearchKeys provides a mock function with given fields: ctx, usage
func (_m *MockSearchKeysSource) SearchKeys(ctx context.Context, usage models.KeyUsage) ([]*dao.KeyEntity, error) {
	ret := _m.Called(ctx, usage)

	if len(ret) == 0 {
		panic("no return value specified for SearchKeys")
	}

	var r0 []*dao.KeyEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.KeyUsage) ([]*dao.KeyEntity, error)); ok {
		return rf(ctx, usage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.KeyUsage) []*dao.KeyEntity); ok {
		r0 = rf(ctx, usage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.KeyEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.KeyUsage) error); ok {
		r1 = rf(ctx, usage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearchKeysSource_SearchKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchKeys'
type MockSearchKeysSource_SearchKeys_Call struct {
	*mock.Call
}

// SearchKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - usage models.KeyUsage
func (_e *MockSearchKeysSource_Expecter) SearchKeys(ctx interface{}, usage interface{}) *MockSearchKeysSource_SearchKeys_Call {
	return &MockSearchKeysSource_SearchKeys_Call{Call: _e.mock.On("SearchKeys", ctx, usage)}
}

func (_c *MockSearchKeysSource_SearchKeys_Call) Run(run func(ctx context.Context, usage models.KeyUsage)) *MockSearchKeysSource_SearchKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.KeyUsage))
	})
	return _c
}

func (_c *MockSearchKeysSource_SearchKeys_Call) Return(_a0 []*dao.KeyEntity, _a1 error) *MockSearchKeysSource_SearchKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearchKeysSource_SearchKeys_Call) RunAndReturn(run func(context.Context, models.KeyUsage) ([]*dao.KeyEntity, error)) *MockSearchKeysSource_SearchKeys_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSearchKeysSource creates a new instance of MockSearchKeysSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchKeysSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchKeysSource {
	mock := &MockSearchKeysSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
