// Code generated by mockery v2.53.1. DO NOT EDIT.

package servicesmocks

import (
	context "github.com/a-novel-kit/context"
	dao "github.com/a-novel/authentication/internal/dao"
	mock "github.com/stretchr/testify/mock"
)

// MockListUsersSource is an autogenerated mock type for the ListUsersSource type
type MockListUsersSource struct {
	mock.Mock
}

type MockListUsersSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListUsersSource) EXPECT() *MockListUsersSource_Expecter {
	return &MockListUsersSource_Expecter{mock: &_m.Mock}
}

// ListUsers provides a mock function with given fields: ctx, data
func (_m *MockListUsersSource) ListUsers(ctx context.Context, data dao.ListUsersData) ([]*dao.CredentialsEntity, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*dao.CredentialsEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dao.ListUsersData) ([]*dao.CredentialsEntity, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dao.ListUsersData) []*dao.CredentialsEntity); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.CredentialsEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dao.ListUsersData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListUsersSource_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockListUsersSource_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - data dao.ListUsersData
func (_e *MockListUsersSource_Expecter) ListUsers(ctx interface{}, data interface{}) *MockListUsersSource_ListUsers_Call {
	return &MockListUsersSource_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, data)}
}

func (_c *MockListUsersSource_ListUsers_Call) Run(run func(ctx context.Context, data dao.ListUsersData)) *MockListUsersSource_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dao.ListUsersData))
	})
	return _c
}

func (_c *MockListUsersSource_ListUsers_Call) Return(_a0 []*dao.CredentialsEntity, _a1 error) *MockListUsersSource_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListUsersSource_ListUsers_Call) RunAndReturn(run func(context.Context, dao.ListUsersData) ([]*dao.CredentialsEntity, error)) *MockListUsersSource_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListUsersSource creates a new instance of MockListUsersSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListUsersSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListUsersSource {
	mock := &MockListUsersSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
