// Code generated by mockery v2.53.1. DO NOT EDIT.

package servicesmocks

import (
	context "github.com/a-novel-kit/context"
	dao "github.com/a-novel/service-authentication/internal/dao"
	mock "github.com/stretchr/testify/mock"

	services "github.com/a-novel/service-authentication/internal/services"
)

// MockLoginSource is an autogenerated mock type for the LoginSource type
type MockLoginSource struct {
	mock.Mock
}

type MockLoginSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginSource) EXPECT() *MockLoginSource_Expecter {
	return &MockLoginSource_Expecter{mock: &_m.Mock}
}

// IssueToken provides a mock function with given fields: ctx, request
func (_m *MockLoginSource) IssueToken(ctx context.Context, request services.IssueTokenRequest) (string, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for IssueToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.IssueTokenRequest) (string, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.IssueTokenRequest) string); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.IssueTokenRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginSource_IssueToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueToken'
type MockLoginSource_IssueToken_Call struct {
	*mock.Call
}

// IssueToken is a helper method to define mock.On call
//   - ctx context.Context
//   - request services.IssueTokenRequest
func (_e *MockLoginSource_Expecter) IssueToken(ctx interface{}, request interface{}) *MockLoginSource_IssueToken_Call {
	return &MockLoginSource_IssueToken_Call{Call: _e.mock.On("IssueToken", ctx, request)}
}

func (_c *MockLoginSource_IssueToken_Call) Run(run func(ctx context.Context, request services.IssueTokenRequest)) *MockLoginSource_IssueToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.IssueTokenRequest))
	})
	return _c
}

func (_c *MockLoginSource_IssueToken_Call) Return(_a0 string, _a1 error) *MockLoginSource_IssueToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoginSource_IssueToken_Call) RunAndReturn(run func(context.Context, services.IssueTokenRequest) (string, error)) *MockLoginSource_IssueToken_Call {
	_c.Call.Return(run)
	return _c
}

// SelectCredentialsByEmail provides a mock function with given fields: ctx, email
func (_m *MockLoginSource) SelectCredentialsByEmail(ctx context.Context, email string) (*dao.CredentialsEntity, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for SelectCredentialsByEmail")
	}

	var r0 *dao.CredentialsEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dao.CredentialsEntity, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dao.CredentialsEntity); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.CredentialsEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginSource_SelectCredentialsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectCredentialsByEmail'
type MockLoginSource_SelectCredentialsByEmail_Call struct {
	*mock.Call
}

// SelectCredentialsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockLoginSource_Expecter) SelectCredentialsByEmail(ctx interface{}, email interface{}) *MockLoginSource_SelectCredentialsByEmail_Call {
	return &MockLoginSource_SelectCredentialsByEmail_Call{Call: _e.mock.On("SelectCredentialsByEmail", ctx, email)}
}

func (_c *MockLoginSource_SelectCredentialsByEmail_Call) Run(run func(ctx context.Context, email string)) *MockLoginSource_SelectCredentialsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLoginSource_SelectCredentialsByEmail_Call) Return(_a0 *dao.CredentialsEntity, _a1 error) *MockLoginSource_SelectCredentialsByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoginSource_SelectCredentialsByEmail_Call) RunAndReturn(run func(context.Context, string) (*dao.CredentialsEntity, error)) *MockLoginSource_SelectCredentialsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginSource creates a new instance of MockLoginSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginSource {
	mock := &MockLoginSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
