// Code generated by mockery v2.52.2. DO NOT EDIT.

package servicesmocks

import (
	context "github.com/a-novel-kit/context"
	dao "github.com/a-novel/authentication/internal/dao"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSelectKeySource is an autogenerated mock type for the SelectKeySource type
type MockSelectKeySource struct {
	mock.Mock
}

type MockSelectKeySource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSelectKeySource) EXPECT() *MockSelectKeySource_Expecter {
	return &MockSelectKeySource_Expecter{mock: &_m.Mock}
}

// SelectKey provides a mock function with given fields: ctx, id
func (_m *MockSelectKeySource) SelectKey(ctx context.Context, id uuid.UUID) (*dao.KeyEntity, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SelectKey")
	}

	var r0 *dao.KeyEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dao.KeyEntity, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dao.KeyEntity); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.KeyEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSelectKeySource_SelectKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectKey'
type MockSelectKeySource_SelectKey_Call struct {
	*mock.Call
}

// SelectKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSelectKeySource_Expecter) SelectKey(ctx interface{}, id interface{}) *MockSelectKeySource_SelectKey_Call {
	return &MockSelectKeySource_SelectKey_Call{Call: _e.mock.On("SelectKey", ctx, id)}
}

func (_c *MockSelectKeySource_SelectKey_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSelectKeySource_SelectKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSelectKeySource_SelectKey_Call) Return(_a0 *dao.KeyEntity, _a1 error) *MockSelectKeySource_SelectKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSelectKeySource_SelectKey_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*dao.KeyEntity, error)) *MockSelectKeySource_SelectKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSelectKeySource creates a new instance of MockSelectKeySource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSelectKeySource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSelectKeySource {
	mock := &MockSelectKeySource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
