// Code generated by mockery v2.53.1. DO NOT EDIT.

package servicesmocks

import (
	context "github.com/a-novel-kit/context"
	mock "github.com/stretchr/testify/mock"

	models "github.com/a-novel/service-authentication/models"

	services "github.com/a-novel/service-authentication/internal/services"
)

// MockRequestEmailUpdateSource is an autogenerated mock type for the RequestEmailUpdateSource type
type MockRequestEmailUpdateSource struct {
	mock.Mock
}

type MockRequestEmailUpdateSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestEmailUpdateSource) EXPECT() *MockRequestEmailUpdateSource_Expecter {
	return &MockRequestEmailUpdateSource_Expecter{mock: &_m.Mock}
}

// CreateShortCode provides a mock function with given fields: ctx, request
func (_m *MockRequestEmailUpdateSource) CreateShortCode(ctx context.Context, request services.CreateShortCodeRequest) (*models.ShortCode, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortCode")
	}

	var r0 *models.ShortCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.CreateShortCodeRequest) (*models.ShortCode, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.CreateShortCodeRequest) *models.ShortCode); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ShortCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.CreateShortCodeRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestEmailUpdateSource_CreateShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortCode'
type MockRequestEmailUpdateSource_CreateShortCode_Call struct {
	*mock.Call
}

// CreateShortCode is a helper method to define mock.On call
//   - ctx context.Context
//   - request services.CreateShortCodeRequest
func (_e *MockRequestEmailUpdateSource_Expecter) CreateShortCode(ctx interface{}, request interface{}) *MockRequestEmailUpdateSource_CreateShortCode_Call {
	return &MockRequestEmailUpdateSource_CreateShortCode_Call{Call: _e.mock.On("CreateShortCode", ctx, request)}
}

func (_c *MockRequestEmailUpdateSource_CreateShortCode_Call) Run(run func(ctx context.Context, request services.CreateShortCodeRequest)) *MockRequestEmailUpdateSource_CreateShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.CreateShortCodeRequest))
	})
	return _c
}

func (_c *MockRequestEmailUpdateSource_CreateShortCode_Call) Return(_a0 *models.ShortCode, _a1 error) *MockRequestEmailUpdateSource_CreateShortCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestEmailUpdateSource_CreateShortCode_Call) RunAndReturn(run func(context.Context, services.CreateShortCodeRequest) (*models.ShortCode, error)) *MockRequestEmailUpdateSource_CreateShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequestEmailUpdateSource creates a new instance of MockRequestEmailUpdateSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestEmailUpdateSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestEmailUpdateSource {
	mock := &MockRequestEmailUpdateSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
