// Code generated by mockery v2.53.1. DO NOT EDIT.

package servicesmocks

import (
	context "github.com/a-novel-kit/context"
	dao "github.com/a-novel/service-authentication/internal/dao"
	mock "github.com/stretchr/testify/mock"
)

// MockCreateShortCodeSource is an autogenerated mock type for the CreateShortCodeSource type
type MockCreateShortCodeSource struct {
	mock.Mock
}

type MockCreateShortCodeSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateShortCodeSource) EXPECT() *MockCreateShortCodeSource_Expecter {
	return &MockCreateShortCodeSource_Expecter{mock: &_m.Mock}
}

// InsertShortCode provides a mock function with given fields: ctx, data
func (_m *MockCreateShortCodeSource) InsertShortCode(ctx context.Context, data dao.InsertShortCodeData) (*dao.ShortCodeEntity, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for InsertShortCode")
	}

	var r0 *dao.ShortCodeEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dao.InsertShortCodeData) (*dao.ShortCodeEntity, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dao.InsertShortCodeData) *dao.ShortCodeEntity); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.ShortCodeEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dao.InsertShortCodeData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateShortCodeSource_InsertShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertShortCode'
type MockCreateShortCodeSource_InsertShortCode_Call struct {
	*mock.Call
}

// InsertShortCode is a helper method to define mock.On call
//   - ctx context.Context
//   - data dao.InsertShortCodeData
func (_e *MockCreateShortCodeSource_Expecter) InsertShortCode(ctx interface{}, data interface{}) *MockCreateShortCodeSource_InsertShortCode_Call {
	return &MockCreateShortCodeSource_InsertShortCode_Call{Call: _e.mock.On("InsertShortCode", ctx, data)}
}

func (_c *MockCreateShortCodeSource_InsertShortCode_Call) Run(run func(ctx context.Context, data dao.InsertShortCodeData)) *MockCreateShortCodeSource_InsertShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dao.InsertShortCodeData))
	})
	return _c
}

func (_c *MockCreateShortCodeSource_InsertShortCode_Call) Return(_a0 *dao.ShortCodeEntity, _a1 error) *MockCreateShortCodeSource_InsertShortCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateShortCodeSource_InsertShortCode_Call) RunAndReturn(run func(context.Context, dao.InsertShortCodeData) (*dao.ShortCodeEntity, error)) *MockCreateShortCodeSource_InsertShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateShortCodeSource creates a new instance of MockCreateShortCodeSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateShortCodeSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateShortCodeSource {
	mock := &MockCreateShortCodeSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
