// Code generated by mockery v2.53.1. DO NOT EDIT.

package apimocks

import (
	context "github.com/a-novel-kit/context"
	mock "github.com/stretchr/testify/mock"

	models "github.com/a-novel/service-authentication/models"

	services "github.com/a-novel/service-authentication/internal/services"
)

// MockGetUserService is an autogenerated mock type for the GetUserService type
type MockGetUserService struct {
	mock.Mock
}

type MockGetUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetUserService) EXPECT() *MockGetUserService_Expecter {
	return &MockGetUserService_Expecter{mock: &_m.Mock}
}

// SelectUser provides a mock function with given fields: ctx, request
func (_m *MockGetUserService) SelectUser(ctx context.Context, request services.SelectUserRequest) (*models.User, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SelectUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.SelectUserRequest) (*models.User, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.SelectUserRequest) *models.User); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.SelectUserRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetUserService_SelectUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectUser'
type MockGetUserService_SelectUser_Call struct {
	*mock.Call
}

// SelectUser is a helper method to define mock.On call
//   - ctx context.Context
//   - request services.SelectUserRequest
func (_e *MockGetUserService_Expecter) SelectUser(ctx interface{}, request interface{}) *MockGetUserService_SelectUser_Call {
	return &MockGetUserService_SelectUser_Call{Call: _e.mock.On("SelectUser", ctx, request)}
}

func (_c *MockGetUserService_SelectUser_Call) Run(run func(ctx context.Context, request services.SelectUserRequest)) *MockGetUserService_SelectUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.SelectUserRequest))
	})
	return _c
}

func (_c *MockGetUserService_SelectUser_Call) Return(_a0 *models.User, _a1 error) *MockGetUserService_SelectUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetUserService_SelectUser_Call) RunAndReturn(run func(context.Context, services.SelectUserRequest) (*models.User, error)) *MockGetUserService_SelectUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetUserService creates a new instance of MockGetUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetUserService {
	mock := &MockGetUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
