// Code generated by mockery v2.53.1. DO NOT EDIT.

package apimocks

import (
	context "github.com/a-novel-kit/context"
	mock "github.com/stretchr/testify/mock"

	models "github.com/a-novel/service-authentication/models"

	services "github.com/a-novel/service-authentication/internal/services"
)

// MockRequestEmailUpdateService is an autogenerated mock type for the RequestEmailUpdateService type
type MockRequestEmailUpdateService struct {
	mock.Mock
}

type MockRequestEmailUpdateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestEmailUpdateService) EXPECT() *MockRequestEmailUpdateService_Expecter {
	return &MockRequestEmailUpdateService_Expecter{mock: &_m.Mock}
}

// RequestEmailUpdate provides a mock function with given fields: ctx, request
func (_m *MockRequestEmailUpdateService) RequestEmailUpdate(ctx context.Context, request services.RequestEmailUpdateRequest) (*models.ShortCode, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for RequestEmailUpdate")
	}

	var r0 *models.ShortCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.RequestEmailUpdateRequest) (*models.ShortCode, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.RequestEmailUpdateRequest) *models.ShortCode); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ShortCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.RequestEmailUpdateRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestEmailUpdateService_RequestEmailUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestEmailUpdate'
type MockRequestEmailUpdateService_RequestEmailUpdate_Call struct {
	*mock.Call
}

// RequestEmailUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - request services.RequestEmailUpdateRequest
func (_e *MockRequestEmailUpdateService_Expecter) RequestEmailUpdate(ctx interface{}, request interface{}) *MockRequestEmailUpdateService_RequestEmailUpdate_Call {
	return &MockRequestEmailUpdateService_RequestEmailUpdate_Call{Call: _e.mock.On("RequestEmailUpdate", ctx, request)}
}

func (_c *MockRequestEmailUpdateService_RequestEmailUpdate_Call) Run(run func(ctx context.Context, request services.RequestEmailUpdateRequest)) *MockRequestEmailUpdateService_RequestEmailUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.RequestEmailUpdateRequest))
	})
	return _c
}

func (_c *MockRequestEmailUpdateService_RequestEmailUpdate_Call) Return(_a0 *models.ShortCode, _a1 error) *MockRequestEmailUpdateService_RequestEmailUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestEmailUpdateService_RequestEmailUpdate_Call) RunAndReturn(run func(context.Context, services.RequestEmailUpdateRequest) (*models.ShortCode, error)) *MockRequestEmailUpdateService_RequestEmailUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequestEmailUpdateService creates a new instance of MockRequestEmailUpdateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestEmailUpdateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestEmailUpdateService {
	mock := &MockRequestEmailUpdateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
