// Code generated by mockery v2.53.1. DO NOT EDIT.

package apimocks

import (
	context "github.com/a-novel-kit/context"
	mock "github.com/stretchr/testify/mock"

	services "github.com/a-novel/service-authentication/internal/services"
)

// MockRegisterService is an autogenerated mock type for the RegisterService type
type MockRegisterService struct {
	mock.Mock
}

type MockRegisterService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegisterService) EXPECT() *MockRegisterService_Expecter {
	return &MockRegisterService_Expecter{mock: &_m.Mock}
}

// Register provides a mock function with given fields: ctx, request
func (_m *MockRegisterService) Register(ctx context.Context, request services.RegisterRequest) (string, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.RegisterRequest) (string, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.RegisterRequest) string); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.RegisterRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegisterService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRegisterService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - request services.RegisterRequest
func (_e *MockRegisterService_Expecter) Register(ctx interface{}, request interface{}) *MockRegisterService_Register_Call {
	return &MockRegisterService_Register_Call{Call: _e.mock.On("Register", ctx, request)}
}

func (_c *MockRegisterService_Register_Call) Run(run func(ctx context.Context, request services.RegisterRequest)) *MockRegisterService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.RegisterRequest))
	})
	return _c
}

func (_c *MockRegisterService_Register_Call) Return(_a0 string, _a1 error) *MockRegisterService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegisterService_Register_Call) RunAndReturn(run func(context.Context, services.RegisterRequest) (string, error)) *MockRegisterService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegisterService creates a new instance of MockRegisterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegisterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegisterService {
	mock := &MockRegisterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
