// Code generated by mockery v2.52.2. DO NOT EDIT.

package apimocks

import (
	context "github.com/a-novel-kit/context"
	mock "github.com/stretchr/testify/mock"

	services "github.com/a-novel/authentication/internal/services"
)

// MockIssueRefreshTokenService is an autogenerated mock type for the IssueRefreshTokenService type
type MockIssueRefreshTokenService struct {
	mock.Mock
}

type MockIssueRefreshTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIssueRefreshTokenService) EXPECT() *MockIssueRefreshTokenService_Expecter {
	return &MockIssueRefreshTokenService_Expecter{mock: &_m.Mock}
}

// IssueRefreshToken provides a mock function with given fields: ctx, request
func (_m *MockIssueRefreshTokenService) IssueRefreshToken(ctx context.Context, request services.IssueRefreshTokenRequest) (string, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for IssueRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.IssueRefreshTokenRequest) (string, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.IssueRefreshTokenRequest) string); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.IssueRefreshTokenRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIssueRefreshTokenService_IssueRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueRefreshToken'
type MockIssueRefreshTokenService_IssueRefreshToken_Call struct {
	*mock.Call
}

// IssueRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - request services.IssueRefreshTokenRequest
func (_e *MockIssueRefreshTokenService_Expecter) IssueRefreshToken(ctx interface{}, request interface{}) *MockIssueRefreshTokenService_IssueRefreshToken_Call {
	return &MockIssueRefreshTokenService_IssueRefreshToken_Call{Call: _e.mock.On("IssueRefreshToken", ctx, request)}
}

func (_c *MockIssueRefreshTokenService_IssueRefreshToken_Call) Run(run func(ctx context.Context, request services.IssueRefreshTokenRequest)) *MockIssueRefreshTokenService_IssueRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.IssueRefreshTokenRequest))
	})
	return _c
}

func (_c *MockIssueRefreshTokenService_IssueRefreshToken_Call) Return(_a0 string, _a1 error) *MockIssueRefreshTokenService_IssueRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIssueRefreshTokenService_IssueRefreshToken_Call) RunAndReturn(run func(context.Context, services.IssueRefreshTokenRequest) (string, error)) *MockIssueRefreshTokenService_IssueRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIssueRefreshTokenService creates a new instance of MockIssueRefreshTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIssueRefreshTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIssueRefreshTokenService {
	mock := &MockIssueRefreshTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
