// Code generated by mockery v2.53.1. DO NOT EDIT.

package apimocks

import (
	context "github.com/a-novel-kit/context"
	jwa "github.com/a-novel-kit/jwt/jwa"

	mock "github.com/stretchr/testify/mock"

	services "github.com/a-novel/authentication/internal/services"
)

// MockSelectKeyService is an autogenerated mock type for the SelectKeyService type
type MockSelectKeyService struct {
	mock.Mock
}

type MockSelectKeyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSelectKeyService) EXPECT() *MockSelectKeyService_Expecter {
	return &MockSelectKeyService_Expecter{mock: &_m.Mock}
}

// SelectKey provides a mock function with given fields: ctx, request
func (_m *MockSelectKeyService) SelectKey(ctx context.Context, request services.SelectKeyRequest) (*jwa.JWK, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SelectKey")
	}

	var r0 *jwa.JWK
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.SelectKeyRequest) (*jwa.JWK, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.SelectKeyRequest) *jwa.JWK); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwa.JWK)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.SelectKeyRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSelectKeyService_SelectKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectKey'
type MockSelectKeyService_SelectKey_Call struct {
	*mock.Call
}

// SelectKey is a helper method to define mock.On call
//   - ctx context.Context
//   - request services.SelectKeyRequest
func (_e *MockSelectKeyService_Expecter) SelectKey(ctx interface{}, request interface{}) *MockSelectKeyService_SelectKey_Call {
	return &MockSelectKeyService_SelectKey_Call{Call: _e.mock.On("SelectKey", ctx, request)}
}

func (_c *MockSelectKeyService_SelectKey_Call) Run(run func(ctx context.Context, request services.SelectKeyRequest)) *MockSelectKeyService_SelectKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.SelectKeyRequest))
	})
	return _c
}

func (_c *MockSelectKeyService_SelectKey_Call) Return(_a0 *jwa.JWK, _a1 error) *MockSelectKeyService_SelectKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSelectKeyService_SelectKey_Call) RunAndReturn(run func(context.Context, services.SelectKeyRequest) (*jwa.JWK, error)) *MockSelectKeyService_SelectKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSelectKeyService creates a new instance of MockSelectKeyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSelectKeyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSelectKeyService {
	mock := &MockSelectKeyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
