// Code generated by mockery v2.52.2. DO NOT EDIT.

package apimocks

import (
	context "github.com/a-novel-kit/context"
	mock "github.com/stretchr/testify/mock"

	services "github.com/a-novel/authentication/internal/services"
)

// MockEmailExistsService is an autogenerated mock type for the EmailExistsService type
type MockEmailExistsService struct {
	mock.Mock
}

type MockEmailExistsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailExistsService) EXPECT() *MockEmailExistsService_Expecter {
	return &MockEmailExistsService_Expecter{mock: &_m.Mock}
}

// EmailExists provides a mock function with given fields: ctx, request
func (_m *MockEmailExistsService) EmailExists(ctx context.Context, request services.EmailExistsRequest) (bool, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for EmailExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.EmailExistsRequest) (bool, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.EmailExistsRequest) bool); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.EmailExistsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmailExistsService_EmailExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmailExists'
type MockEmailExistsService_EmailExists_Call struct {
	*mock.Call
}

// EmailExists is a helper method to define mock.On call
//   - ctx context.Context
//   - request services.EmailExistsRequest
func (_e *MockEmailExistsService_Expecter) EmailExists(ctx interface{}, request interface{}) *MockEmailExistsService_EmailExists_Call {
	return &MockEmailExistsService_EmailExists_Call{Call: _e.mock.On("EmailExists", ctx, request)}
}

func (_c *MockEmailExistsService_EmailExists_Call) Run(run func(ctx context.Context, request services.EmailExistsRequest)) *MockEmailExistsService_EmailExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.EmailExistsRequest))
	})
	return _c
}

func (_c *MockEmailExistsService_EmailExists_Call) Return(_a0 bool, _a1 error) *MockEmailExistsService_EmailExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmailExistsService_EmailExists_Call) RunAndReturn(run func(context.Context, services.EmailExistsRequest) (bool, error)) *MockEmailExistsService_EmailExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailExistsService creates a new instance of MockEmailExistsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailExistsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailExistsService {
	mock := &MockEmailExistsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
