// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"context"
	"text/template"

	"github.com/a-novel-kit/golib/smtp"
	"github.com/a-novel/service-authentication/v2/internal/core"
	"github.com/a-novel/service-json-keys/v2/pkg/go"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockCredentialsCreateService creates a new instance of MockCredentialsCreateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialsCreateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialsCreateService {
	mock := &MockCredentialsCreateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCredentialsCreateService is an autogenerated mock type for the CredentialsCreateService type
type MockCredentialsCreateService struct {
	mock.Mock
}

type MockCredentialsCreateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialsCreateService) EXPECT() *MockCredentialsCreateService_Expecter {
	return &MockCredentialsCreateService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockCredentialsCreateService
func (_mock *MockCredentialsCreateService) Exec(ctx context.Context, request *core.CredentialsCreateRequest) (*core.Token, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsCreateRequest) (*core.Token, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsCreateRequest) *core.Token); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.CredentialsCreateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialsCreateService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCredentialsCreateService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.CredentialsCreateRequest
func (_e *MockCredentialsCreateService_Expecter) Exec(ctx any, request any) *MockCredentialsCreateService_Exec_Call {
	return &MockCredentialsCreateService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockCredentialsCreateService_Exec_Call) Run(run func(ctx context.Context, request *core.CredentialsCreateRequest)) *MockCredentialsCreateService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.CredentialsCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*core.CredentialsCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCredentialsCreateService_Exec_Call) Return(token *core.Token, err error) *MockCredentialsCreateService_Exec_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockCredentialsCreateService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.CredentialsCreateRequest) (*core.Token, error)) *MockCredentialsCreateService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialsExistService creates a new instance of MockCredentialsExistService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialsExistService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialsExistService {
	mock := &MockCredentialsExistService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCredentialsExistService is an autogenerated mock type for the CredentialsExistService type
type MockCredentialsExistService struct {
	mock.Mock
}

type MockCredentialsExistService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialsExistService) EXPECT() *MockCredentialsExistService_Expecter {
	return &MockCredentialsExistService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockCredentialsExistService
func (_mock *MockCredentialsExistService) Exec(ctx context.Context, request *core.CredentialsExistRequest) (bool, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsExistRequest) (bool, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsExistRequest) bool); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.CredentialsExistRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialsExistService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCredentialsExistService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.CredentialsExistRequest
func (_e *MockCredentialsExistService_Expecter) Exec(ctx any, request any) *MockCredentialsExistService_Exec_Call {
	return &MockCredentialsExistService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockCredentialsExistService_Exec_Call) Run(run func(ctx context.Context, request *core.CredentialsExistRequest)) *MockCredentialsExistService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.CredentialsExistRequest
		if args[1] != nil {
			arg1 = args[1].(*core.CredentialsExistRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCredentialsExistService_Exec_Call) Return(b bool, err error) *MockCredentialsExistService_Exec_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCredentialsExistService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.CredentialsExistRequest) (bool, error)) *MockCredentialsExistService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialsGetService creates a new instance of MockCredentialsGetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialsGetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialsGetService {
	mock := &MockCredentialsGetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCredentialsGetService is an autogenerated mock type for the CredentialsGetService type
type MockCredentialsGetService struct {
	mock.Mock
}

type MockCredentialsGetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialsGetService) EXPECT() *MockCredentialsGetService_Expecter {
	return &MockCredentialsGetService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockCredentialsGetService
func (_mock *MockCredentialsGetService) Exec(ctx context.Context, request *core.CredentialsGetRequest) (*core.Credentials, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Credentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsGetRequest) (*core.Credentials, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsGetRequest) *core.Credentials); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Credentials)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.CredentialsGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialsGetService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCredentialsGetService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.CredentialsGetRequest
func (_e *MockCredentialsGetService_Expecter) Exec(ctx any, request any) *MockCredentialsGetService_Exec_Call {
	return &MockCredentialsGetService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockCredentialsGetService_Exec_Call) Run(run func(ctx context.Context, request *core.CredentialsGetRequest)) *MockCredentialsGetService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.CredentialsGetRequest
		if args[1] != nil {
			arg1 = args[1].(*core.CredentialsGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCredentialsGetService_Exec_Call) Return(credentials *core.Credentials, err error) *MockCredentialsGetService_Exec_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *MockCredentialsGetService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.CredentialsGetRequest) (*core.Credentials, error)) *MockCredentialsGetService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialsListService creates a new instance of MockCredentialsListService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialsListService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialsListService {
	mock := &MockCredentialsListService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCredentialsListService is an autogenerated mock type for the CredentialsListService type
type MockCredentialsListService struct {
	mock.Mock
}

type MockCredentialsListService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialsListService) EXPECT() *MockCredentialsListService_Expecter {
	return &MockCredentialsListService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockCredentialsListService
func (_mock *MockCredentialsListService) Exec(ctx context.Context, request *core.CredentialsListRequest) ([]*core.Credentials, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*core.Credentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsListRequest) ([]*core.Credentials, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsListRequest) []*core.Credentials); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.Credentials)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.CredentialsListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialsListService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCredentialsListService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.CredentialsListRequest
func (_e *MockCredentialsListService_Expecter) Exec(ctx any, request any) *MockCredentialsListService_Exec_Call {
	return &MockCredentialsListService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockCredentialsListService_Exec_Call) Run(run func(ctx context.Context, request *core.CredentialsListRequest)) *MockCredentialsListService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.CredentialsListRequest
		if args[1] != nil {
			arg1 = args[1].(*core.CredentialsListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCredentialsListService_Exec_Call) Return(credentialss []*core.Credentials, err error) *MockCredentialsListService_Exec_Call {
	_c.Call.Return(credentialss, err)
	return _c
}

func (_c *MockCredentialsListService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.CredentialsListRequest) ([]*core.Credentials, error)) *MockCredentialsListService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialsResetPasswordService creates a new instance of MockCredentialsResetPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialsResetPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialsResetPasswordService {
	mock := &MockCredentialsResetPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCredentialsResetPasswordService is an autogenerated mock type for the CredentialsResetPasswordService type
type MockCredentialsResetPasswordService struct {
	mock.Mock
}

type MockCredentialsResetPasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialsResetPasswordService) EXPECT() *MockCredentialsResetPasswordService_Expecter {
	return &MockCredentialsResetPasswordService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockCredentialsResetPasswordService
func (_mock *MockCredentialsResetPasswordService) Exec(ctx context.Context, request *core.CredentialsUpdatePasswordRequest) (*core.Credentials, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Credentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsUpdatePasswordRequest) (*core.Credentials, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsUpdatePasswordRequest) *core.Credentials); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Credentials)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.CredentialsUpdatePasswordRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialsResetPasswordService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCredentialsResetPasswordService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.CredentialsUpdatePasswordRequest
func (_e *MockCredentialsResetPasswordService_Expecter) Exec(ctx any, request any) *MockCredentialsResetPasswordService_Exec_Call {
	return &MockCredentialsResetPasswordService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockCredentialsResetPasswordService_Exec_Call) Run(run func(ctx context.Context, request *core.CredentialsUpdatePasswordRequest)) *MockCredentialsResetPasswordService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.CredentialsUpdatePasswordRequest
		if args[1] != nil {
			arg1 = args[1].(*core.CredentialsUpdatePasswordRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCredentialsResetPasswordService_Exec_Call) Return(credentials *core.Credentials, err error) *MockCredentialsResetPasswordService_Exec_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *MockCredentialsResetPasswordService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.CredentialsUpdatePasswordRequest) (*core.Credentials, error)) *MockCredentialsResetPasswordService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialsUpdateEmailService creates a new instance of MockCredentialsUpdateEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialsUpdateEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialsUpdateEmailService {
	mock := &MockCredentialsUpdateEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCredentialsUpdateEmailService is an autogenerated mock type for the CredentialsUpdateEmailService type
type MockCredentialsUpdateEmailService struct {
	mock.Mock
}

type MockCredentialsUpdateEmailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialsUpdateEmailService) EXPECT() *MockCredentialsUpdateEmailService_Expecter {
	return &MockCredentialsUpdateEmailService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockCredentialsUpdateEmailService
func (_mock *MockCredentialsUpdateEmailService) Exec(ctx context.Context, request *core.CredentialsUpdateEmailRequest) (*core.Credentials, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Credentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsUpdateEmailRequest) (*core.Credentials, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsUpdateEmailRequest) *core.Credentials); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Credentials)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.CredentialsUpdateEmailRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialsUpdateEmailService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCredentialsUpdateEmailService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.CredentialsUpdateEmailRequest
func (_e *MockCredentialsUpdateEmailService_Expecter) Exec(ctx any, request any) *MockCredentialsUpdateEmailService_Exec_Call {
	return &MockCredentialsUpdateEmailService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockCredentialsUpdateEmailService_Exec_Call) Run(run func(ctx context.Context, request *core.CredentialsUpdateEmailRequest)) *MockCredentialsUpdateEmailService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.CredentialsUpdateEmailRequest
		if args[1] != nil {
			arg1 = args[1].(*core.CredentialsUpdateEmailRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCredentialsUpdateEmailService_Exec_Call) Return(credentials *core.Credentials, err error) *MockCredentialsUpdateEmailService_Exec_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *MockCredentialsUpdateEmailService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.CredentialsUpdateEmailRequest) (*core.Credentials, error)) *MockCredentialsUpdateEmailService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialsUpdatePasswordService creates a new instance of MockCredentialsUpdatePasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialsUpdatePasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialsUpdatePasswordService {
	mock := &MockCredentialsUpdatePasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCredentialsUpdatePasswordService is an autogenerated mock type for the CredentialsUpdatePasswordService type
type MockCredentialsUpdatePasswordService struct {
	mock.Mock
}

type MockCredentialsUpdatePasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialsUpdatePasswordService) EXPECT() *MockCredentialsUpdatePasswordService_Expecter {
	return &MockCredentialsUpdatePasswordService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockCredentialsUpdatePasswordService
func (_mock *MockCredentialsUpdatePasswordService) Exec(ctx context.Context, request *core.CredentialsUpdatePasswordRequest) (*core.Credentials, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Credentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsUpdatePasswordRequest) (*core.Credentials, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsUpdatePasswordRequest) *core.Credentials); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Credentials)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.CredentialsUpdatePasswordRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialsUpdatePasswordService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCredentialsUpdatePasswordService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.CredentialsUpdatePasswordRequest
func (_e *MockCredentialsUpdatePasswordService_Expecter) Exec(ctx any, request any) *MockCredentialsUpdatePasswordService_Exec_Call {
	return &MockCredentialsUpdatePasswordService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockCredentialsUpdatePasswordService_Exec_Call) Run(run func(ctx context.Context, request *core.CredentialsUpdatePasswordRequest)) *MockCredentialsUpdatePasswordService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.CredentialsUpdatePasswordRequest
		if args[1] != nil {
			arg1 = args[1].(*core.CredentialsUpdatePasswordRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCredentialsUpdatePasswordService_Exec_Call) Return(credentials *core.Credentials, err error) *MockCredentialsUpdatePasswordService_Exec_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *MockCredentialsUpdatePasswordService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.CredentialsUpdatePasswordRequest) (*core.Credentials, error)) *MockCredentialsUpdatePasswordService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialsUpdateRoleService creates a new instance of MockCredentialsUpdateRoleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialsUpdateRoleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialsUpdateRoleService {
	mock := &MockCredentialsUpdateRoleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCredentialsUpdateRoleService is an autogenerated mock type for the CredentialsUpdateRoleService type
type MockCredentialsUpdateRoleService struct {
	mock.Mock
}

type MockCredentialsUpdateRoleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialsUpdateRoleService) EXPECT() *MockCredentialsUpdateRoleService_Expecter {
	return &MockCredentialsUpdateRoleService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockCredentialsUpdateRoleService
func (_mock *MockCredentialsUpdateRoleService) Exec(ctx context.Context, request *core.CredentialsUpdateRoleRequest) (*core.Credentials, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Credentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsUpdateRoleRequest) (*core.Credentials, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.CredentialsUpdateRoleRequest) *core.Credentials); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Credentials)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.CredentialsUpdateRoleRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialsUpdateRoleService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCredentialsUpdateRoleService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.CredentialsUpdateRoleRequest
func (_e *MockCredentialsUpdateRoleService_Expecter) Exec(ctx any, request any) *MockCredentialsUpdateRoleService_Exec_Call {
	return &MockCredentialsUpdateRoleService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockCredentialsUpdateRoleService_Exec_Call) Run(run func(ctx context.Context, request *core.CredentialsUpdateRoleRequest)) *MockCredentialsUpdateRoleService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.CredentialsUpdateRoleRequest
		if args[1] != nil {
			arg1 = args[1].(*core.CredentialsUpdateRoleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCredentialsUpdateRoleService_Exec_Call) Return(credentials *core.Credentials, err error) *MockCredentialsUpdateRoleService_Exec_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *MockCredentialsUpdateRoleService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.CredentialsUpdateRoleRequest) (*core.Credentials, error)) *MockCredentialsUpdateRoleService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestHealthClientSmtp creates a new instance of MockRestHealthClientSmtp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestHealthClientSmtp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestHealthClientSmtp {
	mock := &MockRestHealthClientSmtp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestHealthClientSmtp is an autogenerated mock type for the RestHealthClientSmtp type
type MockRestHealthClientSmtp struct {
	mock.Mock
}

type MockRestHealthClientSmtp_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestHealthClientSmtp) EXPECT() *MockRestHealthClientSmtp_Expecter {
	return &MockRestHealthClientSmtp_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type MockRestHealthClientSmtp
func (_mock *MockRestHealthClientSmtp) Ping() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRestHealthClientSmtp_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockRestHealthClientSmtp_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockRestHealthClientSmtp_Expecter) Ping() *MockRestHealthClientSmtp_Ping_Call {
	return &MockRestHealthClientSmtp_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockRestHealthClientSmtp_Ping_Call) Run(run func()) *MockRestHealthClientSmtp_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRestHealthClientSmtp_Ping_Call) Return(err error) *MockRestHealthClientSmtp_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRestHealthClientSmtp_Ping_Call) RunAndReturn(run func() error) *MockRestHealthClientSmtp_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// SendMail provides a mock function for the type MockRestHealthClientSmtp
func (_mock *MockRestHealthClientSmtp) SendMail(to smtp.MailUsers, t *template.Template, tName string, data any) error {
	ret := _mock.Called(to, t, tName, data)

	if len(ret) == 0 {
		panic("no return value specified for SendMail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(smtp.MailUsers, *template.Template, string, any) error); ok {
		r0 = returnFunc(to, t, tName, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRestHealthClientSmtp_SendMail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMail'
type MockRestHealthClientSmtp_SendMail_Call struct {
	*mock.Call
}

// SendMail is a helper method to define mock.On call
//   - to smtp.MailUsers
//   - t *template.Template
//   - tName string
//   - data any
func (_e *MockRestHealthClientSmtp_Expecter) SendMail(to any, t any, tName any, data any) *MockRestHealthClientSmtp_SendMail_Call {
	return &MockRestHealthClientSmtp_SendMail_Call{Call: _e.mock.On("SendMail", to, t, tName, data)}
}

func (_c *MockRestHealthClientSmtp_SendMail_Call) Run(run func(to smtp.MailUsers, t *template.Template, tName string, data any)) *MockRestHealthClientSmtp_SendMail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 smtp.MailUsers
		if args[0] != nil {
			arg0 = args[0].(smtp.MailUsers)
		}
		var arg1 *template.Template
		if args[1] != nil {
			arg1 = args[1].(*template.Template)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRestHealthClientSmtp_SendMail_Call) Return(err error) *MockRestHealthClientSmtp_SendMail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRestHealthClientSmtp_SendMail_Call) RunAndReturn(run func(to smtp.MailUsers, t *template.Template, tName string, data any) error) *MockRestHealthClientSmtp_SendMail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestHealthApiJsonKeys creates a new instance of MockRestHealthApiJsonKeys. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestHealthApiJsonKeys(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestHealthApiJsonKeys {
	mock := &MockRestHealthApiJsonKeys{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestHealthApiJsonKeys is an autogenerated mock type for the RestHealthApiJsonKeys type
type MockRestHealthApiJsonKeys struct {
	mock.Mock
}

type MockRestHealthApiJsonKeys_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestHealthApiJsonKeys) EXPECT() *MockRestHealthApiJsonKeys_Expecter {
	return &MockRestHealthApiJsonKeys_Expecter{mock: &_m.Mock}
}

// Status provides a mock function for the type MockRestHealthApiJsonKeys
func (_mock *MockRestHealthApiJsonKeys) Status(ctx context.Context, req *servicejsonkeys.StatusRequest, opts ...grpc.CallOption) (*servicejsonkeys.StatusResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *servicejsonkeys.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejsonkeys.StatusRequest, ...grpc.CallOption) (*servicejsonkeys.StatusResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejsonkeys.StatusRequest, ...grpc.CallOption) *servicejsonkeys.StatusResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicejsonkeys.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *servicejsonkeys.StatusRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestHealthApiJsonKeys_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockRestHealthApiJsonKeys_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - req *servicejsonkeys.StatusRequest
//   - opts ...grpc.CallOption
func (_e *MockRestHealthApiJsonKeys_Expecter) Status(ctx any, req any, opts ...any) *MockRestHealthApiJsonKeys_Status_Call {
	return &MockRestHealthApiJsonKeys_Status_Call{Call: _e.mock.On("Status",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockRestHealthApiJsonKeys_Status_Call) Run(run func(ctx context.Context, req *servicejsonkeys.StatusRequest, opts ...grpc.CallOption)) *MockRestHealthApiJsonKeys_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *servicejsonkeys.StatusRequest
		if args[1] != nil {
			arg1 = args[1].(*servicejsonkeys.StatusRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRestHealthApiJsonKeys_Status_Call) Return(v *servicejsonkeys.StatusResponse, err error) *MockRestHealthApiJsonKeys_Status_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRestHealthApiJsonKeys_Status_Call) RunAndReturn(run func(ctx context.Context, req *servicejsonkeys.StatusRequest, opts ...grpc.CallOption) (*servicejsonkeys.StatusResponse, error)) *MockRestHealthApiJsonKeys_Status_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockShortCodeCreateEmailUpdateService creates a new instance of MockShortCodeCreateEmailUpdateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortCodeCreateEmailUpdateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortCodeCreateEmailUpdateService {
	mock := &MockShortCodeCreateEmailUpdateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortCodeCreateEmailUpdateService is an autogenerated mock type for the ShortCodeCreateEmailUpdateService type
type MockShortCodeCreateEmailUpdateService struct {
	mock.Mock
}

type MockShortCodeCreateEmailUpdateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortCodeCreateEmailUpdateService) EXPECT() *MockShortCodeCreateEmailUpdateService_Expecter {
	return &MockShortCodeCreateEmailUpdateService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockShortCodeCreateEmailUpdateService
func (_mock *MockShortCodeCreateEmailUpdateService) Exec(ctx context.Context, request *core.ShortCodeCreateEmailUpdateRequest) (*core.ShortCode, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.ShortCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ShortCodeCreateEmailUpdateRequest) (*core.ShortCode, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ShortCodeCreateEmailUpdateRequest) *core.ShortCode); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.ShortCode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ShortCodeCreateEmailUpdateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortCodeCreateEmailUpdateService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockShortCodeCreateEmailUpdateService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ShortCodeCreateEmailUpdateRequest
func (_e *MockShortCodeCreateEmailUpdateService_Expecter) Exec(ctx any, request any) *MockShortCodeCreateEmailUpdateService_Exec_Call {
	return &MockShortCodeCreateEmailUpdateService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockShortCodeCreateEmailUpdateService_Exec_Call) Run(run func(ctx context.Context, request *core.ShortCodeCreateEmailUpdateRequest)) *MockShortCodeCreateEmailUpdateService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ShortCodeCreateEmailUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ShortCodeCreateEmailUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortCodeCreateEmailUpdateService_Exec_Call) Return(shortCode *core.ShortCode, err error) *MockShortCodeCreateEmailUpdateService_Exec_Call {
	_c.Call.Return(shortCode, err)
	return _c
}

func (_c *MockShortCodeCreateEmailUpdateService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ShortCodeCreateEmailUpdateRequest) (*core.ShortCode, error)) *MockShortCodeCreateEmailUpdateService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockShortCodeCreatePasswordResetService creates a new instance of MockShortCodeCreatePasswordResetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortCodeCreatePasswordResetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortCodeCreatePasswordResetService {
	mock := &MockShortCodeCreatePasswordResetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortCodeCreatePasswordResetService is an autogenerated mock type for the ShortCodeCreatePasswordResetService type
type MockShortCodeCreatePasswordResetService struct {
	mock.Mock
}

type MockShortCodeCreatePasswordResetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortCodeCreatePasswordResetService) EXPECT() *MockShortCodeCreatePasswordResetService_Expecter {
	return &MockShortCodeCreatePasswordResetService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockShortCodeCreatePasswordResetService
func (_mock *MockShortCodeCreatePasswordResetService) Exec(ctx context.Context, request *core.ShortCodeCreatePasswordResetRequest) (*core.ShortCode, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.ShortCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ShortCodeCreatePasswordResetRequest) (*core.ShortCode, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ShortCodeCreatePasswordResetRequest) *core.ShortCode); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.ShortCode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ShortCodeCreatePasswordResetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortCodeCreatePasswordResetService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockShortCodeCreatePasswordResetService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ShortCodeCreatePasswordResetRequest
func (_e *MockShortCodeCreatePasswordResetService_Expecter) Exec(ctx any, request any) *MockShortCodeCreatePasswordResetService_Exec_Call {
	return &MockShortCodeCreatePasswordResetService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockShortCodeCreatePasswordResetService_Exec_Call) Run(run func(ctx context.Context, request *core.ShortCodeCreatePasswordResetRequest)) *MockShortCodeCreatePasswordResetService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ShortCodeCreatePasswordResetRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ShortCodeCreatePasswordResetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortCodeCreatePasswordResetService_Exec_Call) Return(shortCode *core.ShortCode, err error) *MockShortCodeCreatePasswordResetService_Exec_Call {
	_c.Call.Return(shortCode, err)
	return _c
}

func (_c *MockShortCodeCreatePasswordResetService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ShortCodeCreatePasswordResetRequest) (*core.ShortCode, error)) *MockShortCodeCreatePasswordResetService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockShortCodeCreateRegisterService creates a new instance of MockShortCodeCreateRegisterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortCodeCreateRegisterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortCodeCreateRegisterService {
	mock := &MockShortCodeCreateRegisterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortCodeCreateRegisterService is an autogenerated mock type for the ShortCodeCreateRegisterService type
type MockShortCodeCreateRegisterService struct {
	mock.Mock
}

type MockShortCodeCreateRegisterService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortCodeCreateRegisterService) EXPECT() *MockShortCodeCreateRegisterService_Expecter {
	return &MockShortCodeCreateRegisterService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockShortCodeCreateRegisterService
func (_mock *MockShortCodeCreateRegisterService) Exec(ctx context.Context, request *core.ShortCodeCreateRegisterRequest) (*core.ShortCode, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.ShortCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ShortCodeCreateRegisterRequest) (*core.ShortCode, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ShortCodeCreateRegisterRequest) *core.ShortCode); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.ShortCode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ShortCodeCreateRegisterRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortCodeCreateRegisterService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockShortCodeCreateRegisterService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ShortCodeCreateRegisterRequest
func (_e *MockShortCodeCreateRegisterService_Expecter) Exec(ctx any, request any) *MockShortCodeCreateRegisterService_Exec_Call {
	return &MockShortCodeCreateRegisterService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockShortCodeCreateRegisterService_Exec_Call) Run(run func(ctx context.Context, request *core.ShortCodeCreateRegisterRequest)) *MockShortCodeCreateRegisterService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ShortCodeCreateRegisterRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ShortCodeCreateRegisterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortCodeCreateRegisterService_Exec_Call) Return(shortCode *core.ShortCode, err error) *MockShortCodeCreateRegisterService_Exec_Call {
	_c.Call.Return(shortCode, err)
	return _c
}

func (_c *MockShortCodeCreateRegisterService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ShortCodeCreateRegisterRequest) (*core.ShortCode, error)) *MockShortCodeCreateRegisterService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenCreateService creates a new instance of MockTokenCreateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenCreateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenCreateService {
	mock := &MockTokenCreateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenCreateService is an autogenerated mock type for the TokenCreateService type
type MockTokenCreateService struct {
	mock.Mock
}

type MockTokenCreateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenCreateService) EXPECT() *MockTokenCreateService_Expecter {
	return &MockTokenCreateService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockTokenCreateService
func (_mock *MockTokenCreateService) Exec(ctx context.Context, request *core.TokenCreateRequest) (*core.Token, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.TokenCreateRequest) (*core.Token, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.TokenCreateRequest) *core.Token); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.TokenCreateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenCreateService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockTokenCreateService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.TokenCreateRequest
func (_e *MockTokenCreateService_Expecter) Exec(ctx any, request any) *MockTokenCreateService_Exec_Call {
	return &MockTokenCreateService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockTokenCreateService_Exec_Call) Run(run func(ctx context.Context, request *core.TokenCreateRequest)) *MockTokenCreateService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.TokenCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*core.TokenCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenCreateService_Exec_Call) Return(token *core.Token, err error) *MockTokenCreateService_Exec_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenCreateService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.TokenCreateRequest) (*core.Token, error)) *MockTokenCreateService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenCreateAnonService creates a new instance of MockTokenCreateAnonService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenCreateAnonService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenCreateAnonService {
	mock := &MockTokenCreateAnonService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenCreateAnonService is an autogenerated mock type for the TokenCreateAnonService type
type MockTokenCreateAnonService struct {
	mock.Mock
}

type MockTokenCreateAnonService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenCreateAnonService) EXPECT() *MockTokenCreateAnonService_Expecter {
	return &MockTokenCreateAnonService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockTokenCreateAnonService
func (_mock *MockTokenCreateAnonService) Exec(ctx context.Context) (*core.Token, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*core.Token, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *core.Token); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenCreateAnonService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockTokenCreateAnonService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTokenCreateAnonService_Expecter) Exec(ctx any) *MockTokenCreateAnonService_Exec_Call {
	return &MockTokenCreateAnonService_Exec_Call{Call: _e.mock.On("Exec", ctx)}
}

func (_c *MockTokenCreateAnonService_Exec_Call) Run(run func(ctx context.Context)) *MockTokenCreateAnonService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenCreateAnonService_Exec_Call) Return(token *core.Token, err error) *MockTokenCreateAnonService_Exec_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenCreateAnonService_Exec_Call) RunAndReturn(run func(ctx context.Context) (*core.Token, error)) *MockTokenCreateAnonService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRefreshService creates a new instance of MockTokenRefreshService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRefreshService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRefreshService {
	mock := &MockTokenRefreshService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenRefreshService is an autogenerated mock type for the TokenRefreshService type
type MockTokenRefreshService struct {
	mock.Mock
}

type MockTokenRefreshService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRefreshService) EXPECT() *MockTokenRefreshService_Expecter {
	return &MockTokenRefreshService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockTokenRefreshService
func (_mock *MockTokenRefreshService) Exec(ctx context.Context, request *core.TokenRefreshRequest) (*core.Token, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.TokenRefreshRequest) (*core.Token, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.TokenRefreshRequest) *core.Token); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.TokenRefreshRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRefreshService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockTokenRefreshService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.TokenRefreshRequest
func (_e *MockTokenRefreshService_Expecter) Exec(ctx any, request any) *MockTokenRefreshService_Exec_Call {
	return &MockTokenRefreshService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockTokenRefreshService_Exec_Call) Run(run func(ctx context.Context, request *core.TokenRefreshRequest)) *MockTokenRefreshService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.TokenRefreshRequest
		if args[1] != nil {
			arg1 = args[1].(*core.TokenRefreshRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRefreshService_Exec_Call) Return(token *core.Token, err error) *MockTokenRefreshService_Exec_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenRefreshService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.TokenRefreshRequest) (*core.Token, error)) *MockTokenRefreshService_Exec_Call {
	_c.Call.Return(run)
	return _c
}
